version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library   # Устанавливаем базу данных для основной работы
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Монтируем папку с SQL-скриптами
    networks:
      - backend  # Сеть для изоляции сервисов, если нужно

volumes:
  postgres_data:

networks:
  backend:  # Сеть для изоляции сервисов
    driver: bridge
